[package]
name = "pseudoengine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0"
chrono = "0.4.39"
serde_json = "1.0.139"